Check private key secret

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -24,6 +24,10 @@ jobs:
         run: |
           echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 -d > ./terraform/credentials.json
 
+          if [ -z "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY_B64 }}" ]; then
+            echo "Error: ANSIBLE_SSH_PRIVATE_KEY_B64 secret is not set" >&2
+            exit 1
+          fi
       - name: Terraform Init
         run: terraform init
         working-directory: ./terraform
